#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCJJG.Web.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TCJJGWeb")]
	public partial class TCJJGWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public TCJJGWebDataContext() : 
				base(global::TCJJG.Web.DB.Properties.Settings.Default.TCJJGWebConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TCJJGWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCJJGWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCJJGWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TCJJGWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_CompetitionCenter_GetDetailByID")]
		public ISingleResult<proc_CompetitionCenter_GetDetailByIDResult> proc_CompetitionCenter_GetDetailByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<proc_CompetitionCenter_GetDetailByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_CompetitionCenter_SelectInfo")]
		public ISingleResult<proc_CompetitionCenter_SelectInfoResult> proc_CompetitionCenter_SelectInfo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_CompetitionCenter_SelectInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_CompetitionReport_SelectCompetitionReport")]
		public ISingleResult<proc_CompetitionReport_SelectCompetitionReportResult> proc_CompetitionReport_SelectCompetitionReport()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_CompetitionReport_SelectCompetitionReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_HelpCenter_GetDetail_HelpInfo")]
		public ISingleResult<proc_HelpCenter_GetDetail_HelpInfoResult> proc_HelpCenter_GetDetail_HelpInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HelpID", DbType="Int")] System.Nullable<int> helpID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), helpID);
			return ((ISingleResult<proc_HelpCenter_GetDetail_HelpInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_HelpCenter_GetHelpInfoByHelpType")]
		public ISingleResult<proc_HelpCenter_GetHelpInfoByHelpTypeResult> proc_HelpCenter_GetHelpInfoByHelpType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HelpType", DbType="Int")] System.Nullable<int> helpType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rowCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), helpType, pageIndex, pageSize, rowCount);
			rowCount = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<proc_HelpCenter_GetHelpInfoByHelpTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_FAQ_SelectInfoList")]
		public ISingleResult<proc_FAQ_SelectInfoListResult> proc_FAQ_SelectInfoList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_FAQ_SelectInfoListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_MaintenancePage_SelectPageInfo")]
		public ISingleResult<proc_MaintenancePage_SelectPageInfoResult> proc_MaintenancePage_SelectPageInfo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_MaintenancePage_SelectPageInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Yu_IndexAD_Sel_Img")]
		public ISingleResult<Yu_IndexAD_Sel_ImgResult> Yu_IndexAD_Sel_Img()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Yu_IndexAD_Sel_ImgResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_IndexPage_GetPageAllContent")]
		public ISingleResult<proc_IndexPage_GetPageAllContentResult> proc_IndexPage_GetPageAllContent()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_IndexPage_GetPageAllContentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FWP_News_ByType")]
		public ISingleResult<FWP_News_ByTypeResult> FWP_News_ByType([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> typeBase, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> newsTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageCount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> pageTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> newsTypeID1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(32)")] ref string newsTypeName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), typeBase, newsTypeID, pageIndex, pageCount, pageTotal, newsTypeID1, newsTypeName);
			pageTotal = ((System.Nullable<int>)(result.GetParameterValue(4)));
			newsTypeID1 = ((System.Nullable<int>)(result.GetParameterValue(5)));
			newsTypeName = ((string)(result.GetParameterValue(6)));
			return ((ISingleResult<FWP_News_ByTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FWP_News_SelectContent")]
		public ISingleResult<FWP_News_SelectContentResult> FWP_News_SelectContent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsID", DbType="Int")] System.Nullable<int> newsID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last", DbType="Int")] ref System.Nullable<int> last, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Next", DbType="Int")] ref System.Nullable<int> next)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newsID, last, next);
			last = ((System.Nullable<int>)(result.GetParameterValue(1)));
			next = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<FWP_News_SelectContentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_FWT_News_Comment")]
		public int proc_FWT_News_Comment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewsID", DbType="Int")] System.Nullable<int> newsID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP", DbType="NVarChar(32)")] string iP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommentType", DbType="Int")] System.Nullable<int> commentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewCount", DbType="Int")] ref System.Nullable<int> newCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), newsID, iP, commentType, newCount);
			newCount = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class proc_CompetitionCenter_GetDetailByIDResult
	{
		
		private int _ID;
		
		private string _IndexImgUrl;
		
		private string _MoreListImgUrl;
		
		private int _Sort;
		
		private string _LinkToDetail;
		
		private string _DetailedContent;
		
		public proc_CompetitionCenter_GetDetailByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexImgUrl", DbType="NVarChar(1024)")]
		public string IndexImgUrl
		{
			get
			{
				return this._IndexImgUrl;
			}
			set
			{
				if ((this._IndexImgUrl != value))
				{
					this._IndexImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreListImgUrl", DbType="NVarChar(1024)")]
		public string MoreListImgUrl
		{
			get
			{
				return this._MoreListImgUrl;
			}
			set
			{
				if ((this._MoreListImgUrl != value))
				{
					this._MoreListImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkToDetail", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string LinkToDetail
		{
			get
			{
				return this._LinkToDetail;
			}
			set
			{
				if ((this._LinkToDetail != value))
				{
					this._LinkToDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailedContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DetailedContent
		{
			get
			{
				return this._DetailedContent;
			}
			set
			{
				if ((this._DetailedContent != value))
				{
					this._DetailedContent = value;
				}
			}
		}
	}
	
	public partial class proc_CompetitionCenter_SelectInfoResult
	{
		
		private int _ID;
		
		private string _IndexImgUrl;
		
		private string _MoreListImgUrl;
		
		private int _Sort;
		
		private string _LinkToDetail;
		
		private string _DetailedContent;
		
		public proc_CompetitionCenter_SelectInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexImgUrl", DbType="NVarChar(1024)")]
		public string IndexImgUrl
		{
			get
			{
				return this._IndexImgUrl;
			}
			set
			{
				if ((this._IndexImgUrl != value))
				{
					this._IndexImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreListImgUrl", DbType="NVarChar(1024)")]
		public string MoreListImgUrl
		{
			get
			{
				return this._MoreListImgUrl;
			}
			set
			{
				if ((this._MoreListImgUrl != value))
				{
					this._MoreListImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkToDetail", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string LinkToDetail
		{
			get
			{
				return this._LinkToDetail;
			}
			set
			{
				if ((this._LinkToDetail != value))
				{
					this._LinkToDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailedContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DetailedContent
		{
			get
			{
				return this._DetailedContent;
			}
			set
			{
				if ((this._DetailedContent != value))
				{
					this._DetailedContent = value;
				}
			}
		}
	}
	
	public partial class proc_CompetitionReport_SelectCompetitionReportResult
	{
		
		private int _CompetitionID;
		
		private string _CompetitionImgUrl;
		
		private string _CompetitionTitle;
		
		private string _CompetitionContent;
		
		private string _CompetitionLinkToUrl;
		
		private int _CompetitionSort;
		
		public proc_CompetitionReport_SelectCompetitionReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionID", DbType="Int NOT NULL")]
		public int CompetitionID
		{
			get
			{
				return this._CompetitionID;
			}
			set
			{
				if ((this._CompetitionID != value))
				{
					this._CompetitionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionImgUrl", DbType="NVarChar(1024)")]
		public string CompetitionImgUrl
		{
			get
			{
				return this._CompetitionImgUrl;
			}
			set
			{
				if ((this._CompetitionImgUrl != value))
				{
					this._CompetitionImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionTitle", DbType="NVarChar(256)")]
		public string CompetitionTitle
		{
			get
			{
				return this._CompetitionTitle;
			}
			set
			{
				if ((this._CompetitionTitle != value))
				{
					this._CompetitionTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionContent", DbType="NVarChar(1024)")]
		public string CompetitionContent
		{
			get
			{
				return this._CompetitionContent;
			}
			set
			{
				if ((this._CompetitionContent != value))
				{
					this._CompetitionContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionLinkToUrl", DbType="NVarChar(1024)")]
		public string CompetitionLinkToUrl
		{
			get
			{
				return this._CompetitionLinkToUrl;
			}
			set
			{
				if ((this._CompetitionLinkToUrl != value))
				{
					this._CompetitionLinkToUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompetitionSort", DbType="Int NOT NULL")]
		public int CompetitionSort
		{
			get
			{
				return this._CompetitionSort;
			}
			set
			{
				if ((this._CompetitionSort != value))
				{
					this._CompetitionSort = value;
				}
			}
		}
	}
	
	public partial class proc_HelpCenter_GetDetail_HelpInfoResult
	{
		
		private string _HelpName;
		
		private int _HelpType;
		
		private int _HelpSort;
		
		private string _HelpContent;
		
		public proc_HelpCenter_GetDetail_HelpInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string HelpName
		{
			get
			{
				return this._HelpName;
			}
			set
			{
				if ((this._HelpName != value))
				{
					this._HelpName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpType", DbType="Int NOT NULL")]
		public int HelpType
		{
			get
			{
				return this._HelpType;
			}
			set
			{
				if ((this._HelpType != value))
				{
					this._HelpType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpSort", DbType="Int NOT NULL")]
		public int HelpSort
		{
			get
			{
				return this._HelpSort;
			}
			set
			{
				if ((this._HelpSort != value))
				{
					this._HelpSort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string HelpContent
		{
			get
			{
				return this._HelpContent;
			}
			set
			{
				if ((this._HelpContent != value))
				{
					this._HelpContent = value;
				}
			}
		}
	}
	
	public partial class proc_HelpCenter_GetHelpInfoByHelpTypeResult
	{
		
		private int _HelpID;
		
		private string _HelpName;
		
		private int _HelpType;
		
		private int _HelpSort;
		
		private System.Nullable<long> _num;
		
		public proc_HelpCenter_GetHelpInfoByHelpTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpID", DbType="Int NOT NULL")]
		public int HelpID
		{
			get
			{
				return this._HelpID;
			}
			set
			{
				if ((this._HelpID != value))
				{
					this._HelpID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string HelpName
		{
			get
			{
				return this._HelpName;
			}
			set
			{
				if ((this._HelpName != value))
				{
					this._HelpName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpType", DbType="Int NOT NULL")]
		public int HelpType
		{
			get
			{
				return this._HelpType;
			}
			set
			{
				if ((this._HelpType != value))
				{
					this._HelpType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpSort", DbType="Int NOT NULL")]
		public int HelpSort
		{
			get
			{
				return this._HelpSort;
			}
			set
			{
				if ((this._HelpSort != value))
				{
					this._HelpSort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num", DbType="BigInt")]
		public System.Nullable<long> num
		{
			get
			{
				return this._num;
			}
			set
			{
				if ((this._num != value))
				{
					this._num = value;
				}
			}
		}
	}
	
	public partial class proc_FAQ_SelectInfoListResult
	{
		
		private int _FAQID;
		
		private string _FAQTitle;
		
		private int _FAQPosition;
		
		private int _FAQSort;
		
		public proc_FAQ_SelectInfoListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAQID", DbType="Int NOT NULL")]
		public int FAQID
		{
			get
			{
				return this._FAQID;
			}
			set
			{
				if ((this._FAQID != value))
				{
					this._FAQID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAQTitle", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string FAQTitle
		{
			get
			{
				return this._FAQTitle;
			}
			set
			{
				if ((this._FAQTitle != value))
				{
					this._FAQTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAQPosition", DbType="Int NOT NULL")]
		public int FAQPosition
		{
			get
			{
				return this._FAQPosition;
			}
			set
			{
				if ((this._FAQPosition != value))
				{
					this._FAQPosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAQSort", DbType="Int NOT NULL")]
		public int FAQSort
		{
			get
			{
				return this._FAQSort;
			}
			set
			{
				if ((this._FAQSort != value))
				{
					this._FAQSort = value;
				}
			}
		}
	}
	
	public partial class proc_MaintenancePage_SelectPageInfoResult
	{
		
		private string _Contents;
		
		private int _IsApply;
		
		public proc_MaintenancePage_SelectPageInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contents", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Contents
		{
			get
			{
				return this._Contents;
			}
			set
			{
				if ((this._Contents != value))
				{
					this._Contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApply", DbType="Int NOT NULL")]
		public int IsApply
		{
			get
			{
				return this._IsApply;
			}
			set
			{
				if ((this._IsApply != value))
				{
					this._IsApply = value;
				}
			}
		}
	}
	
	public partial class Yu_IndexAD_Sel_ImgResult
	{
		
		private int _ID;
		
		private string _ImageName;
		
		private string _Title;
		
		private string _LinkURL;
		
		private System.Nullable<int> _OpeType;
		
		public Yu_IndexAD_Sel_ImgResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this._ImageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(32)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkURL", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LinkURL
		{
			get
			{
				return this._LinkURL;
			}
			set
			{
				if ((this._LinkURL != value))
				{
					this._LinkURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeType", DbType="Int")]
		public System.Nullable<int> OpeType
		{
			get
			{
				return this._OpeType;
			}
			set
			{
				if ((this._OpeType != value))
				{
					this._OpeType = value;
				}
			}
		}
	}
	
	public partial class proc_IndexPage_GetPageAllContentResult
	{
		
		private int _ID;
		
		private int _PositionType;
		
		private string _TextContent;
		
		public proc_IndexPage_GetPageAllContentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionType", DbType="Int NOT NULL")]
		public int PositionType
		{
			get
			{
				return this._PositionType;
			}
			set
			{
				if ((this._PositionType != value))
				{
					this._PositionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TextContent
		{
			get
			{
				return this._TextContent;
			}
			set
			{
				if ((this._TextContent != value))
				{
					this._TextContent = value;
				}
			}
		}
	}
	
	public partial class FWP_News_ByTypeResult
	{
		
		private int _NewsID;
		
		private string _NewsTitle;
		
		private string _NewsImg;
		
		private string _Brevity;
		
		private string _NewsDate;
		
		private int _newsTypeID;
		
		private System.Nullable<int> _Praise;
		
		private System.Nullable<int> _Batch;
		
		public FWP_News_ByTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsID", DbType="Int NOT NULL")]
		public int NewsID
		{
			get
			{
				return this._NewsID;
			}
			set
			{
				if ((this._NewsID != value))
				{
					this._NewsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsTitle", DbType="NVarChar(64)")]
		public string NewsTitle
		{
			get
			{
				return this._NewsTitle;
			}
			set
			{
				if ((this._NewsTitle != value))
				{
					this._NewsTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsImg", DbType="NVarChar(128)")]
		public string NewsImg
		{
			get
			{
				return this._NewsImg;
			}
			set
			{
				if ((this._NewsImg != value))
				{
					this._NewsImg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brevity", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Brevity
		{
			get
			{
				return this._Brevity;
			}
			set
			{
				if ((this._Brevity != value))
				{
					this._Brevity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="VarChar(20)")]
		public string NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newsTypeID", DbType="Int NOT NULL")]
		public int newsTypeID
		{
			get
			{
				return this._newsTypeID;
			}
			set
			{
				if ((this._newsTypeID != value))
				{
					this._newsTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Praise", DbType="Int")]
		public System.Nullable<int> Praise
		{
			get
			{
				return this._Praise;
			}
			set
			{
				if ((this._Praise != value))
				{
					this._Praise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch", DbType="Int")]
		public System.Nullable<int> Batch
		{
			get
			{
				return this._Batch;
			}
			set
			{
				if ((this._Batch != value))
				{
					this._Batch = value;
				}
			}
		}
	}
	
	public partial class FWP_News_SelectContentResult
	{
		
		private int _NewsID;
		
		private string _NewsTitle;
		
		private string _NewsContent;
		
		private string _NewsDate;
		
		private System.Nullable<int> _NewsCounter;
		
		private string _Brevity;
		
		private string _NewsImg;
		
		private string _newsTypeName;
		
		private System.Nullable<int> _Praise;
		
		private System.Nullable<int> _Batch;
		
		public FWP_News_SelectContentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsID", DbType="Int NOT NULL")]
		public int NewsID
		{
			get
			{
				return this._NewsID;
			}
			set
			{
				if ((this._NewsID != value))
				{
					this._NewsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsTitle", DbType="NVarChar(64)")]
		public string NewsTitle
		{
			get
			{
				return this._NewsTitle;
			}
			set
			{
				if ((this._NewsTitle != value))
				{
					this._NewsTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NewsContent
		{
			get
			{
				return this._NewsContent;
			}
			set
			{
				if ((this._NewsContent != value))
				{
					this._NewsContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="VarChar(20)")]
		public string NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCounter", DbType="Int")]
		public System.Nullable<int> NewsCounter
		{
			get
			{
				return this._NewsCounter;
			}
			set
			{
				if ((this._NewsCounter != value))
				{
					this._NewsCounter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brevity", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Brevity
		{
			get
			{
				return this._Brevity;
			}
			set
			{
				if ((this._Brevity != value))
				{
					this._Brevity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsImg", DbType="NVarChar(128)")]
		public string NewsImg
		{
			get
			{
				return this._NewsImg;
			}
			set
			{
				if ((this._NewsImg != value))
				{
					this._NewsImg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newsTypeName", DbType="NVarChar(32)")]
		public string newsTypeName
		{
			get
			{
				return this._newsTypeName;
			}
			set
			{
				if ((this._newsTypeName != value))
				{
					this._newsTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Praise", DbType="Int")]
		public System.Nullable<int> Praise
		{
			get
			{
				return this._Praise;
			}
			set
			{
				if ((this._Praise != value))
				{
					this._Praise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch", DbType="Int")]
		public System.Nullable<int> Batch
		{
			get
			{
				return this._Batch;
			}
			set
			{
				if ((this._Batch != value))
				{
					this._Batch = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
