//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFJJG.Common.UserCenter
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GangsReckoning", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class GangsReckoning : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CreateTimeField;
        
        private int DirectionField;
        
        private int ItemField;
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        private int SubItemField;
        
        private System.Guid UserIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubItem
        {
            get
            {
                return this.SubItemField;
            }
            set
            {
                this.SubItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGangsControlSvc")]
public interface IGangsControlSvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGangsControlSvc/GangsGetReckoning", ReplyAction="http://tempuri.org/IGangsControlSvc/GangsGetReckoningResponse")]
    FFJJG.Common.UserCenter.Reckoning[] GangsGetReckoning(FFJJG.Common.UserCenter.GangsReckoning gr, ref System.Nullable<int> pageTotal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGangsControlSvcChannel : IGangsControlSvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GangsControlSvcClient : System.ServiceModel.ClientBase<IGangsControlSvc>, IGangsControlSvc
{
    
    public GangsControlSvcClient()
    {
    }
    
    public GangsControlSvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GangsControlSvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GangsControlSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GangsControlSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FFJJG.Common.UserCenter.Reckoning[] GangsGetReckoning(FFJJG.Common.UserCenter.GangsReckoning gr, ref System.Nullable<int> pageTotal)
    {
        return base.Channel.GangsGetReckoning(gr, ref pageTotal);
    }
}
