//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPaySvc")]
public interface IPaySvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/GetTasteCard", ReplyAction="http://tempuri.org/IPaySvc/GetTasteCardResponse")]
    int GetTasteCard(int ope, int cityID, string userName1, string createIP, ref System.Nullable<int> appCount, ref System.Nullable<int> surplusCount, ref string cardPwd);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/CardUse", ReplyAction="http://tempuri.org/IPaySvc/CardUseResponse")]
    int CardUse(string userName1, string userName2, string cardPwdMD5, string createIP, string remarks, ref System.Nullable<int> getRichTypeID, ref System.Nullable<int> cardLogID, ref System.Nullable<int> payAmount, ref System.Nullable<int> getRichAmount, ref System.Nullable<int> cardTypeID, ref System.Nullable<int> cardValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/CardUseCallBack", ReplyAction="http://tempuri.org/IPaySvc/CardUseCallBackResponse")]
    int CardUseCallBack(int cardLogID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/GetCityListByCardBatch", ReplyAction="http://tempuri.org/IPaySvc/GetCityListByCardBatchResponse")]
    int[] GetCityListByCardBatch(string cardID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/YPayInit", ReplyAction="http://tempuri.org/IPaySvc/YPayInitResponse")]
    int YPayInit(string userName1, string userName2, int typeID, int amount, string yFlag, int status, string createIP, string remark);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/YCallBack", ReplyAction="http://tempuri.org/IPaySvc/YCallBackResponse")]
    int YCallBack(int r6_Order, int r3_Amt, string r2_TrxId, string r7_Uid, string rb_BankId, string ro_BankOrderId, string rp_PayDate, string rq_CardNo, string ru_Trxtime, int callBackType, ref string userName1, ref System.Nullable<int> p_Amount, ref System.Nullable<int> c_TypeID, ref System.Nullable<int> c_Amount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/VpayCallBack", ReplyAction="http://tempuri.org/IPaySvc/VpayCallBackResponse")]
    int VpayCallBack(int vpayID, int vpayAmount, string orderID, string bankID, string paydate, string cardID, ref string userName, ref System.Nullable<int> payAmount, ref System.Nullable<int> GetRichType, ref System.Nullable<int> GetRichAmount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/MobilePhoneFeeLogCreate", ReplyAction="http://tempuri.org/IPaySvc/MobilePhoneFeeLogCreateResponse")]
    int MobilePhoneFeeLogCreate(int state, System.Guid userID, int appid, string userName, string mobile, int amount, string memo, ref System.Nullable<int> orderID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/MobilePhoneFeeLogUpdateState", ReplyAction="http://tempuri.org/IPaySvc/MobilePhoneFeeLogUpdateStateResponse")]
    int MobilePhoneFeeLogUpdateState(int orderID, int state, int amount, string mobile, string memo, ref System.Nullable<System.Guid> userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/SMSLogCreate", ReplyAction="http://tempuri.org/IPaySvc/SMSLogCreateResponse")]
    int SMSLogCreate(System.Guid userID, int appid, string userName, string mobile, string msg, string orderID, string memo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/AddAlipayLog", ReplyAction="http://tempuri.org/IPaySvc/AddAlipayLogResponse")]
    int AddAlipayLog(int status, System.Guid userID, int appid, string userName, int amount, string memo, ref System.Nullable<int> orderID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaySvc/AlipayLogUpdateStatus", ReplyAction="http://tempuri.org/IPaySvc/AlipayLogUpdateStatusResponse")]
    int AlipayLogUpdateStatus(int orderID, int status, int amount, string memo, ref System.Nullable<System.Guid> userID, ref string userName, ref System.Nullable<int> payRate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPaySvcChannel : IPaySvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PaySvcClient : System.ServiceModel.ClientBase<IPaySvc>, IPaySvc
{
    
    public PaySvcClient()
    {
    }
    
    public PaySvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PaySvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PaySvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PaySvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetTasteCard(int ope, int cityID, string userName1, string createIP, ref System.Nullable<int> appCount, ref System.Nullable<int> surplusCount, ref string cardPwd)
    {
        return base.Channel.GetTasteCard(ope, cityID, userName1, createIP, ref appCount, ref surplusCount, ref cardPwd);
    }
    
    public int CardUse(string userName1, string userName2, string cardPwdMD5, string createIP, string remarks, ref System.Nullable<int> getRichTypeID, ref System.Nullable<int> cardLogID, ref System.Nullable<int> payAmount, ref System.Nullable<int> getRichAmount, ref System.Nullable<int> cardTypeID, ref System.Nullable<int> cardValue)
    {
        return base.Channel.CardUse(userName1, userName2, cardPwdMD5, createIP, remarks, ref getRichTypeID, ref cardLogID, ref payAmount, ref getRichAmount, ref cardTypeID, ref cardValue);
    }
    
    public int CardUseCallBack(int cardLogID)
    {
        return base.Channel.CardUseCallBack(cardLogID);
    }
    
    public int[] GetCityListByCardBatch(string cardID)
    {
        return base.Channel.GetCityListByCardBatch(cardID);
    }
    
    public int YPayInit(string userName1, string userName2, int typeID, int amount, string yFlag, int status, string createIP, string remark)
    {
        return base.Channel.YPayInit(userName1, userName2, typeID, amount, yFlag, status, createIP, remark);
    }
    
    public int YCallBack(int r6_Order, int r3_Amt, string r2_TrxId, string r7_Uid, string rb_BankId, string ro_BankOrderId, string rp_PayDate, string rq_CardNo, string ru_Trxtime, int callBackType, ref string userName1, ref System.Nullable<int> p_Amount, ref System.Nullable<int> c_TypeID, ref System.Nullable<int> c_Amount)
    {
        return base.Channel.YCallBack(r6_Order, r3_Amt, r2_TrxId, r7_Uid, rb_BankId, ro_BankOrderId, rp_PayDate, rq_CardNo, ru_Trxtime, callBackType, ref userName1, ref p_Amount, ref c_TypeID, ref c_Amount);
    }
    
    public int VpayCallBack(int vpayID, int vpayAmount, string orderID, string bankID, string paydate, string cardID, ref string userName, ref System.Nullable<int> payAmount, ref System.Nullable<int> GetRichType, ref System.Nullable<int> GetRichAmount)
    {
        return base.Channel.VpayCallBack(vpayID, vpayAmount, orderID, bankID, paydate, cardID, ref userName, ref payAmount, ref GetRichType, ref GetRichAmount);
    }
    
    public int MobilePhoneFeeLogCreate(int state, System.Guid userID, int appid, string userName, string mobile, int amount, string memo, ref System.Nullable<int> orderID)
    {
        return base.Channel.MobilePhoneFeeLogCreate(state, userID, appid, userName, mobile, amount, memo, ref orderID);
    }
    
    public int MobilePhoneFeeLogUpdateState(int orderID, int state, int amount, string mobile, string memo, ref System.Nullable<System.Guid> userID)
    {
        return base.Channel.MobilePhoneFeeLogUpdateState(orderID, state, amount, mobile, memo, ref userID);
    }
    
    public int SMSLogCreate(System.Guid userID, int appid, string userName, string mobile, string msg, string orderID, string memo)
    {
        return base.Channel.SMSLogCreate(userID, appid, userName, mobile, msg, orderID, memo);
    }
    
    public int AddAlipayLog(int status, System.Guid userID, int appid, string userName, int amount, string memo, ref System.Nullable<int> orderID)
    {
        return base.Channel.AddAlipayLog(status, userID, appid, userName, amount, memo, ref orderID);
    }
    
    public int AlipayLogUpdateStatus(int orderID, int status, int amount, string memo, ref System.Nullable<System.Guid> userID, ref string userName, ref System.Nullable<int> payRate)
    {
        return base.Channel.AlipayLogUpdateStatus(orderID, status, amount, memo, ref userID, ref userName, ref payRate);
    }
}
