//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFJJG.Common.UserCenter
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RichTypePresenter", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class RichTypePresenter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MinAmountField;
        
        private int PresenteConditionField;
        
        private int PresenterMultipleField;
        
        private int ReceiveConditionField;
        
        private int SortField;
        
        private int StatusField;
        
        private int TaxPercentageField;
        
        private int TypeIDField;
        
        private string TypeNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinAmount
        {
            get
            {
                return this.MinAmountField;
            }
            set
            {
                this.MinAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PresenteCondition
        {
            get
            {
                return this.PresenteConditionField;
            }
            set
            {
                this.PresenteConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PresenterMultiple
        {
            get
            {
                return this.PresenterMultipleField;
            }
            set
            {
                this.PresenterMultipleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiveCondition
        {
            get
            {
                return this.ReceiveConditionField;
            }
            set
            {
                this.ReceiveConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sort
        {
            get
            {
                return this.SortField;
            }
            set
            {
                this.SortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxPercentage
        {
            get
            {
                return this.TaxPercentageField;
            }
            set
            {
                this.TaxPercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeID
        {
            get
            {
                return this.TypeIDField;
            }
            set
            {
                this.TypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RichesExchange", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class RichesExchange : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BaseRichAmountField;
        
        private int BaseRichTypeField;
        
        private int ToRichAmountField;
        
        private int ToRichTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseRichAmount
        {
            get
            {
                return this.BaseRichAmountField;
            }
            set
            {
                this.BaseRichAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseRichType
        {
            get
            {
                return this.BaseRichTypeField;
            }
            set
            {
                this.BaseRichTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToRichAmount
        {
            get
            {
                return this.ToRichAmountField;
            }
            set
            {
                this.ToRichAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToRichType
        {
            get
            {
                return this.ToRichTypeField;
            }
            set
            {
                this.ToRichTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsInfo", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class GoodsInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AField;
        
        private string DField;
        
        private string IField;
        
        private string MField;
        
        private string NField;
        
        private int TField;
        
        private int UField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A
        {
            get
            {
                return this.AField;
            }
            set
            {
                this.AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string D
        {
            get
            {
                return this.DField;
            }
            set
            {
                this.DField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string I
        {
            get
            {
                return this.IField;
            }
            set
            {
                this.IField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string M
        {
            get
            {
                return this.MField;
            }
            set
            {
                this.MField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string N
        {
            get
            {
                return this.NField;
            }
            set
            {
                this.NField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int T
        {
            get
            {
                return this.TField;
            }
            set
            {
                this.TField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int U
        {
            get
            {
                return this.UField;
            }
            set
            {
                this.UField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRichInfoSvc")]
public interface IRichInfoSvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/GiveGood", ReplyAction="http://tempuri.org/IRichInfoSvc/GiveGoodResponse")]
    int GiveGood(System.Guid from, string fromUserName, string recieverUserName, int recieverAppID, int typeID, byte giveType, int amount, System.DateTime dueTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/GetSpecialFunctionInfo", ReplyAction="http://tempuri.org/IRichInfoSvc/GetSpecialFunctionInfoResponse")]
    System.Collections.Generic.Dictionary<int, int[]> GetSpecialFunctionInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/BuyOneProperty", ReplyAction="http://tempuri.org/IRichInfoSvc/BuyOnePropertyResponse")]
    int BuyOneProperty(System.Guid userID, int userType, int propertyTypeID, string propertyTypeName, int count, string memo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/PayLogAdd", ReplyAction="http://tempuri.org/IRichInfoSvc/PayLogAddResponse")]
    int PayLogAdd(int payType, string userName1, string userName2, int payAmount, int getRichType, int getRichAmount, string createIP, string memo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/RichTypePresenterList", ReplyAction="http://tempuri.org/IRichInfoSvc/RichTypePresenterListResponse")]
    FFJJG.Common.UserCenter.RichTypePresenter[] RichTypePresenterList(int cityID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/RichTypePresenter", ReplyAction="http://tempuri.org/IRichInfoSvc/RichTypePresenterResponse")]
    FFJJG.Common.UserCenter.RichTypePresenter RichTypePresenter(int typeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/GetUserCityCoinInfo", ReplyAction="http://tempuri.org/IRichInfoSvc/GetUserCityCoinInfoResponse")]
    void GetUserCityCoinInfo(System.Guid userID, ref System.Nullable<int> richType, ref string typeName, ref System.Nullable<int> amount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/UserRichesExchange", ReplyAction="http://tempuri.org/IRichInfoSvc/UserRichesExchangeResponse")]
    string UserRichesExchange(System.Guid userID, int baseRichType, int toRichType, int baseRichAmount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/GetRichsExchange", ReplyAction="http://tempuri.org/IRichInfoSvc/GetRichsExchangeResponse")]
    FFJJG.Common.UserCenter.RichesExchange GetRichsExchange(int baseRichType, int toRichType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRichInfoSvc/GetUserGoods", ReplyAction="http://tempuri.org/IRichInfoSvc/GetUserGoodsResponse")]
    FFJJG.Common.UserCenter.GoodsInfo[] GetUserGoods(System.Guid userID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRichInfoSvcChannel : IRichInfoSvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RichInfoSvcClient : System.ServiceModel.ClientBase<IRichInfoSvc>, IRichInfoSvc
{
    
    public RichInfoSvcClient()
    {
    }
    
    public RichInfoSvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RichInfoSvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RichInfoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RichInfoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GiveGood(System.Guid from, string fromUserName, string recieverUserName, int recieverAppID, int typeID, byte giveType, int amount, System.DateTime dueTime)
    {
        return base.Channel.GiveGood(from, fromUserName, recieverUserName, recieverAppID, typeID, giveType, amount, dueTime);
    }
    
    public System.Collections.Generic.Dictionary<int, int[]> GetSpecialFunctionInfo()
    {
        return base.Channel.GetSpecialFunctionInfo();
    }
    
    public int BuyOneProperty(System.Guid userID, int userType, int propertyTypeID, string propertyTypeName, int count, string memo)
    {
        return base.Channel.BuyOneProperty(userID, userType, propertyTypeID, propertyTypeName, count, memo);
    }
    
    public int PayLogAdd(int payType, string userName1, string userName2, int payAmount, int getRichType, int getRichAmount, string createIP, string memo)
    {
        return base.Channel.PayLogAdd(payType, userName1, userName2, payAmount, getRichType, getRichAmount, createIP, memo);
    }
    
    public FFJJG.Common.UserCenter.RichTypePresenter[] RichTypePresenterList(int cityID)
    {
        return base.Channel.RichTypePresenterList(cityID);
    }
    
    public FFJJG.Common.UserCenter.RichTypePresenter RichTypePresenter(int typeID)
    {
        return base.Channel.RichTypePresenter(typeID);
    }
    
    public void GetUserCityCoinInfo(System.Guid userID, ref System.Nullable<int> richType, ref string typeName, ref System.Nullable<int> amount)
    {
        base.Channel.GetUserCityCoinInfo(userID, ref richType, ref typeName, ref amount);
    }
    
    public string UserRichesExchange(System.Guid userID, int baseRichType, int toRichType, int baseRichAmount)
    {
        return base.Channel.UserRichesExchange(userID, baseRichType, toRichType, baseRichAmount);
    }
    
    public FFJJG.Common.UserCenter.RichesExchange GetRichsExchange(int baseRichType, int toRichType)
    {
        return base.Channel.GetRichsExchange(baseRichType, toRichType);
    }
    
    public FFJJG.Common.UserCenter.GoodsInfo[] GetUserGoods(System.Guid userID)
    {
        return base.Channel.GetUserGoods(userID);
    }
}
