//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFJJG.Common.UserCenter
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcountInfo", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class AcountInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AField;
        
        private string DField;
        
        private int GIDField;
        
        private string NField;
        
        private int TField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A
        {
            get
            {
                return this.AField;
            }
            set
            {
                this.AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string D
        {
            get
            {
                return this.DField;
            }
            set
            {
                this.DField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GID
        {
            get
            {
                return this.GIDField;
            }
            set
            {
                this.GIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string N
        {
            get
            {
                return this.NField;
            }
            set
            {
                this.NField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int T
        {
            get
            {
                return this.TField;
            }
            set
            {
                this.TField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubItem", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public enum SubItem : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siDeduct = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siHandBack = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siAwarded = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siFill = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siGive = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siSiteOut = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siSiteIn = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siSiteAward = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siCardPay = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siYeePay = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siAward = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siByAdmin = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siCash = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siGiveCard = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siGiveGoods = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siOpenPacket = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        siServiceCharge = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RichDirection", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public enum RichDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        drOut = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rdIn = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reckoning", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class Reckoning : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AMField;
        
        private string AWField;
        
        private string CRField;
        
        private string DIField;
        
        private string ITField;
        
        private string ITEField;
        
        private int MAField;
        
        private int MNField;
        
        private string MemoField;
        
        private int REField;
        
        private System.Guid RidField;
        
        private string SUField;
        
        private string SUBField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AM
        {
            get
            {
                return this.AMField;
            }
            set
            {
                this.AMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AW
        {
            get
            {
                return this.AWField;
            }
            set
            {
                this.AWField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CR
        {
            get
            {
                return this.CRField;
            }
            set
            {
                this.CRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DI
        {
            get
            {
                return this.DIField;
            }
            set
            {
                this.DIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IT
        {
            get
            {
                return this.ITField;
            }
            set
            {
                this.ITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITE
        {
            get
            {
                return this.ITEField;
            }
            set
            {
                this.ITEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MA
        {
            get
            {
                return this.MAField;
            }
            set
            {
                this.MAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MN
        {
            get
            {
                return this.MNField;
            }
            set
            {
                this.MNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RE
        {
            get
            {
                return this.REField;
            }
            set
            {
                this.REField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Rid
        {
            get
            {
                return this.RidField;
            }
            set
            {
                this.RidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SU
        {
            get
            {
                return this.SUField;
            }
            set
            {
                this.SUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUB
        {
            get
            {
                return this.SUBField;
            }
            set
            {
                this.SUBField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountAmount", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class AccountAmount : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmountField;
        
        private string TypeNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReckoningInfo", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public partial class ReckoningInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmountField;
        
        private string AwardNameField;
        
        private string CreateTimeField;
        
        private int DirectionField;
        
        private string ItemNameField;
        
        private string MemoField;
        
        private int RemainField;
        
        private string SubItemNameField;
        
        private int TypeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwardName
        {
            get
            {
                return this.AwardNameField;
            }
            set
            {
                this.AwardNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                this.ItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Remain
        {
            get
            {
                return this.RemainField;
            }
            set
            {
                this.RemainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubItemName
        {
            get
            {
                return this.SubItemNameField;
            }
            set
            {
                this.SubItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeID
        {
            get
            {
                return this.TypeIDField;
            }
            set
            {
                this.TypeIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserAcountSvc")]
public interface IUserAcountSvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/GetUserAccount", ReplyAction="http://tempuri.org/IUserAcountSvc/GetUserAccountResponse")]
    FFJJG.Common.UserCenter.AcountInfo[] GetUserAccount(System.Guid userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/GetAllUserAccount", ReplyAction="http://tempuri.org/IUserAcountSvc/GetAllUserAccountResponse")]
    FFJJG.Common.UserCenter.AcountInfo[] GetAllUserAccount(System.Guid userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UpdateAcount", ReplyAction="http://tempuri.org/IUserAcountSvc/UpdateAcountResponse")]
    int UpdateAcount(int gameID, int item, FFJJG.Common.UserCenter.SubItem subItem, string matchName, string memo, FFJJG.Common.UserCenter.RichDirection direction, System.Guid userID, FFJJG.Common.UserCenter.AcountInfo[] acountInfo, int costRelationType, string key, int matchID, int matchNum);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UserAccountLog4", ReplyAction="http://tempuri.org/IUserAcountSvc/UserAccountLog4Response")]
    int UserAccountLog4(System.Guid userID, int ID, int ProductID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UserReckoningSel", ReplyAction="http://tempuri.org/IUserAcountSvc/UserReckoningSelResponse")]
    FFJJG.Common.UserCenter.Reckoning[] UserReckoningSel(System.Guid userID, string createTime1, string createTime2, int pageIndex, int pageCount, ref System.Nullable<int> pageTotal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UserReckoningSelAmply", ReplyAction="http://tempuri.org/IUserAcountSvc/UserReckoningSelAmplyResponse")]
    string UserReckoningSelAmply(System.Guid userID, System.Guid rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/AccountAmount", ReplyAction="http://tempuri.org/IUserAcountSvc/AccountAmountResponse")]
    FFJJG.Common.UserCenter.AccountAmount AccountAmount(int appid, string userName, int typeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UserRecharge", ReplyAction="http://tempuri.org/IUserAcountSvc/UserRechargeResponse")]
    bool UserRecharge(System.Guid userID, int typeID, int count, int item, int subItem, int direction, string memo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAcountSvc/UserReckoningAmply", ReplyAction="http://tempuri.org/IUserAcountSvc/UserReckoningAmplyResponse")]
    FFJJG.Common.UserCenter.ReckoningInfo UserReckoningAmply(System.Guid userID, System.Guid rid);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserAcountSvcChannel : IUserAcountSvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserAcountSvcClient : System.ServiceModel.ClientBase<IUserAcountSvc>, IUserAcountSvc
{
    
    public UserAcountSvcClient()
    {
    }
    
    public UserAcountSvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserAcountSvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserAcountSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserAcountSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FFJJG.Common.UserCenter.AcountInfo[] GetUserAccount(System.Guid userID)
    {
        return base.Channel.GetUserAccount(userID);
    }
    
    public FFJJG.Common.UserCenter.AcountInfo[] GetAllUserAccount(System.Guid userID)
    {
        return base.Channel.GetAllUserAccount(userID);
    }
    
    public int UpdateAcount(int gameID, int item, FFJJG.Common.UserCenter.SubItem subItem, string matchName, string memo, FFJJG.Common.UserCenter.RichDirection direction, System.Guid userID, FFJJG.Common.UserCenter.AcountInfo[] acountInfo, int costRelationType, string key, int matchID, int matchNum)
    {
        return base.Channel.UpdateAcount(gameID, item, subItem, matchName, memo, direction, userID, acountInfo, costRelationType, key, matchID, matchNum);
    }
    
    public int UserAccountLog4(System.Guid userID, int ID, int ProductID)
    {
        return base.Channel.UserAccountLog4(userID, ID, ProductID);
    }
    
    public FFJJG.Common.UserCenter.Reckoning[] UserReckoningSel(System.Guid userID, string createTime1, string createTime2, int pageIndex, int pageCount, ref System.Nullable<int> pageTotal)
    {
        return base.Channel.UserReckoningSel(userID, createTime1, createTime2, pageIndex, pageCount, ref pageTotal);
    }
    
    public string UserReckoningSelAmply(System.Guid userID, System.Guid rid)
    {
        return base.Channel.UserReckoningSelAmply(userID, rid);
    }
    
    public FFJJG.Common.UserCenter.AccountAmount AccountAmount(int appid, string userName, int typeID)
    {
        return base.Channel.AccountAmount(appid, userName, typeID);
    }
    
    public bool UserRecharge(System.Guid userID, int typeID, int count, int item, int subItem, int direction, string memo)
    {
        return base.Channel.UserRecharge(userID, typeID, count, item, subItem, direction, memo);
    }
    
    public FFJJG.Common.UserCenter.ReckoningInfo UserReckoningAmply(System.Guid userID, System.Guid rid)
    {
        return base.Channel.UserReckoningAmply(userID, rid);
    }
}
