//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFJJG.Common.UserCenter
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.Common.UserCenter")]
    public enum MessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mtPrivate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mtSystem = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mtSocial = 4,
    }
}
namespace FFJJG.UserCenter.Biz
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListMsgTmp", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.UserCenter.Biz")]
    public partial class ListMsgTmp : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RCountField;
        
        private FFJJG.UserCenter.DataAccess.Message[] lsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RCount
        {
            get
            {
                return this.RCountField;
            }
            set
            {
                this.RCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FFJJG.UserCenter.DataAccess.Message[] ls
        {
            get
            {
                return this.lsField;
            }
            set
            {
                this.lsField = value;
            }
        }
    }
}
namespace FFJJG.UserCenter.DataAccess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/FFJJG.UserCenter.DataAccess")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.Guid> FromField;
        
        private short IsReadedField;
        
        private string LinkToField;
        
        private string MsgField;
        
        private int MsgIDField;
        
        private System.DateTime SendTimeField;
        
        private string TitleField;
        
        private System.Guid ToField;
        
        private short TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IsReaded
        {
            get
            {
                return this.IsReadedField;
            }
            set
            {
                this.IsReadedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkTo
        {
            get
            {
                return this.LinkToField;
            }
            set
            {
                this.LinkToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg
        {
            get
            {
                return this.MsgField;
            }
            set
            {
                this.MsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MsgID
        {
            get
            {
                return this.MsgIDField;
            }
            set
            {
                this.MsgIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime
        {
            get
            {
                return this.SendTimeField;
            }
            set
            {
                this.SendTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserMessageSvc")]
public interface IUserMessageSvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/UserSeleMessage", ReplyAction="http://tempuri.org/IUserMessageSvc/UserSeleMessageResponse")]
    string UserSeleMessage(System.Guid userID, int pageIndex, int pageCount, ref System.Nullable<int> pageTotal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/UserSeleMessageAmply", ReplyAction="http://tempuri.org/IUserMessageSvc/UserSeleMessageAmplyResponse")]
    string UserSeleMessageAmply(System.Guid userID, int msgID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/NewMessage", ReplyAction="http://tempuri.org/IUserMessageSvc/NewMessageResponse")]
    int NewMessage(System.Guid to, System.Guid from, FFJJG.Common.UserCenter.MessageType messageType, string title, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/GetUnReadMessageCount", ReplyAction="http://tempuri.org/IUserMessageSvc/GetUnReadMessageCountResponse")]
    int GetUnReadMessageCount(System.Guid userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/GetUserMessage", ReplyAction="http://tempuri.org/IUserMessageSvc/GetUserMessageResponse")]
    FFJJG.UserCenter.Biz.ListMsgTmp GetUserMessage(System.Guid userID, int pageSize, int pageIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserMessageSvc/DeleteMessageByID", ReplyAction="http://tempuri.org/IUserMessageSvc/DeleteMessageByIDResponse")]
    bool DeleteMessageByID(int msgID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserMessageSvcChannel : IUserMessageSvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserMessageSvcClient : System.ServiceModel.ClientBase<IUserMessageSvc>, IUserMessageSvc
{
    
    public UserMessageSvcClient()
    {
    }
    
    public UserMessageSvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserMessageSvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserMessageSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserMessageSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string UserSeleMessage(System.Guid userID, int pageIndex, int pageCount, ref System.Nullable<int> pageTotal)
    {
        return base.Channel.UserSeleMessage(userID, pageIndex, pageCount, ref pageTotal);
    }
    
    public string UserSeleMessageAmply(System.Guid userID, int msgID)
    {
        return base.Channel.UserSeleMessageAmply(userID, msgID);
    }
    
    public int NewMessage(System.Guid to, System.Guid from, FFJJG.Common.UserCenter.MessageType messageType, string title, string msg)
    {
        return base.Channel.NewMessage(to, from, messageType, title, msg);
    }
    
    public int GetUnReadMessageCount(System.Guid userID)
    {
        return base.Channel.GetUnReadMessageCount(userID);
    }
    
    public FFJJG.UserCenter.Biz.ListMsgTmp GetUserMessage(System.Guid userID, int pageSize, int pageIndex)
    {
        return base.Channel.GetUserMessage(userID, pageSize, pageIndex);
    }
    
    public bool DeleteMessageByID(int msgID)
    {
        return base.Channel.DeleteMessageByID(msgID);
    }
}
